server:
  port: 8888
  servlet:
    encoding:
      # 指定项目字符集编码
      charset: UTF-8
      force: true

spring:
  profiles:
    # dev | prod | test
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamer?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: root

mybatis-plus:
  # 存放位置
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 遇到无法映射的字段则进行打印警告
    auto-mapping-unknown-column-behavior: warning
  global-config:
    db-config:
      # 插入时主键类型
      idType: ASSIGN_ID
      # 逻辑删除字段
      logicDeleteField: isdel
      # 删除值
      logicDeleteValue: 1
      # 未删除值
      logicNotDeleteValue: 0

# swagger
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true

